name: CI

on:
  push:
    branches:
      - main
      - wayfire-0.10
  pull_request:
    branches:
      - main
      - wayfire-0.10

permissions: {}

jobs:
  checks:
    name: ${{ matrix.task }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        task:
          - eval
          - lint
          - check-locales
          - test
          - install-staged
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@668647a33843b1f280cb2ef4c41736f86b29f826
      - name: Use the FlakeHub cache
        uses: DeterminateSystems/flakehub-cache-action@9ad836c31b7e8f416874ca582bf19b71cee755d0
      - name: Run ${{ matrix.task }}
        env:
          TASK: ${{ matrix.task }}
        run: nix develop . --command just "$TASK"

  CI:
    name: CI
    if: ${{ !cancelled() }}
    needs:
      - checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Confirm that all checks passed
        env:
          CHECKS_RESULT: ${{ needs.checks.result }}
        run: test "$CHECKS_RESULT" = success
